# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: libstoragemgmt.spec

# add or remove files that should be synced
files_to_sync:
    - libstoragemgmt.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: libstoragemgmt
# downstream (Fedora) RPM package name
downstream_package_name: libstoragemgmt
actions:
    post-upstream-clone: "wget https://src.fedoraproject.org/rpms/libstoragemgmt/raw/main/f/libstoragemgmt.spec -O libstoragemgmt.spec"
    create-archive:
      - ./autogen.sh
      - ./configure
      - make dist
      - bash -c "ls -1 ./libstoragemgmt-*.tar.gz"

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all

srpm_build_deps:
- wget
- tar
- autoconf
- automake
- check-devel
- chrpath
- file
- libtool
- libudev-devel
- libconfig-devel
- gcc
- gcc-c++
- glib2-devel
- python3-devel
- python3-pywbem
- python3-six
- sqlite-devel
- glib2-devel
- valgrind
