#!/bin/bash
#	       
### BEGIN INIT INFO
# Provides: lsmd
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: libStorageMgmt plug-in daemon
### END INIT INFO

. /etc/init.d/functions

NAME=lsmd
EXE=/usr/bin/$NAME
PID=/var/run/lsm/lsmd.pid

RETVAL=0
STATUS=0

if [ "`id -u`" != 0 ] ; then
	echo "Not root"
	exit 4
fi

status_lsm() {
	status -p $PID $NAME > /dev/null 2>&1
	STATUS=$?
}

# See how we were called.
case "$1" in
  start)
	status_lsm
	if [ $STATUS != 0 ] ; then
		$EXE --operation start
		RETVAL=$?
	else	
		RETVAL=$STATUS
	fi
	;;

  force-stop)
	$EXE --operation stop
	RETVAL=$?
	;;

  stop)
	status_lsm
	if [ $STATUS == 0 ] ; then
		$EXE --operation stop
		RETVAL=$?
	else
		RETVAL=0
	fi
	;;

  restart)
	status_lsm
	if [ $STATUS == 0 ] ; then
		$EXE --operation restart
		RETVAL=$?
	else
		$EXE --operation start
		RETVAL=$?
	fi
	;;

  status)
	status -p $PID $NAME
	RETVAL=$?
	;;

  *)
	echo $"Usage: $0 {start|stop|restart|status|force-stop}"
	;;
esac

exit $RETVAL
