#!/usr/bin/env python

# Copyright (C) 2012 Red Hat, Inc.
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
#
# Author: tasleson
import sys
import lsm
from lsm.cmdline import ArgError
import lsm.common
import lsm.client
import lsm.data
import time

#Command line interface for libStorageMgmt.
if __name__ == '__main__':
    try:
        cli = lsm.cmdline.CmdLine()
        cli.process()
    except ArgError as ae:
        sys.stderr.write(str(ae))
        sys.exit(2)
    except lsm.common.LsmError as le:
        sys.stderr.write(str(le) + "\n")
        sys.exit(4)