[package]
name = "lsm-rust"
version = "1.7.0"
authors = ["Gris Ge <fge@redhat.com>"]

[lib]
name = "lsm"

[dependencies]
url = "1.5.1"
serde = "1.0.16"
serde_json = "1.0.4"
serde_derive = "1.0.16"
regex = "0.2.2"
rand = "0.3.18"     # For integration tests only
